---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'myapp'
    vault.hashicorp.com/agent-inject-secret-secrets.txt: 'kv/data/target'      
spec:
  containers:
  - image: busybox
    name: busybox
  serviceAccountName: vault-auth
